version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    networks:
      - tabungan
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    volumes:
      - ./migration/0_init_db.sql:/docker-entrypoint-initdb.d/0_init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 20s
      retries: 5
    restart: on-failure